template/package.json

Hey Dan - Does this look like a good idea?
It should make a file
http://localstudio.good-loop.com/build/npm-compile.gitlog.txt
whenever `npm run compile` is called.
NB: It isn't doing that on live studio -- which I thought it would from CI.
https://studio.good-loop.com/build/npm-compile.gitlog.txt

npm manifest

---

base/components/PropControl.jsx
base/components/PropControlPills.jsx
base/components/PropControls/PropControlImg.jsx
base/components/PropControls/PropControlUpload.jsx
base/components/PropControls/PropControlUrl.jsx

Hello @roscoemcinerney
This looks good. 
I've created a PR, as that seems a nice way to comment. 
I've found an issue with the validators: Testing on http://localstudio.good-loop.com/#widgets?f=money -- it looks like the money validator is being called, but any errors are not being shown to the user.

(by Roscoe) Groundwork for shifting all PropControl types to modules: register and validator refactors

---

base/components/PropControl.jsx
base/components/PropControlAutoComplete.jsx
base/components/PropControls.jsx

Hello @dodo721 
Could you do the honours for code reviewing this PR? 
Thanks - Dan
It moves autocomplete into its own file, and edits it so that options can be `String[]` or `Object[]`

split autocomplete out into own file + handles objects

---

base/searchquery.js

A small change: "campaign:foo" will now parse as `{campaign: foo}` instead of `[campaign, foo]`. Which makes it easier to distinguish from "campaign foo" which parses as a list of keywords, ["AND", "campaign", "foo"].
This _should_ be safe, because I don't think any code pokes inside SearchQuery to look at `.tree`.

A better parse tree format for SearchQuery

---

base/components/MessageBar.jsx
base/plumbing/ServerIOBase.js

before this, 
- if you forgot to start the SoGive server locally & went to http://local.sogive.org/#search, you'd see:
- and if instead the server is running but Elastic Search stops running, you'd see the same thing.
Now,
- if you forget to start the server you see this:
- and if your Elastic Search instance goes down, you see this:
- Also, if you enter a malformed url at http://local.sogive.org/#editordashboard you now see this:
(instead of "Could not load /import.json from the server \nDetails")

Improve error alerts

---

base/components/MainDivBase.jsx
base/components/NavBar.jsx

- Refactor to make existing Navbar `dark` and `color` attributes
optional parameters of MainDivBase.
- This is a no-op for existing clients since it defaults to current
values (`true` and `dark`), but will allow SoGive to switch to a light
theme by setting the parameters to `false` and `white`.

Support light-themed navbar

---

base/components/MainDivBase.jsx
base/components/NavBar.jsx

Required for new SoGive top navbar links (Home, About, Contact, FAQ) to link back to sogive.org links
Also support passing in a 'homeLink' prop to override where the logo in the navbar links to.
Paired with @aissshah on this

Support external navbar links

---

base/components/NavBar.jsx

Turns out you need to explicitly set `light=true` in the reactstrap Navbar component to get light styling. 
Not noticeable on desktop, but on mobile the menu button background image won't be set unless the style is navbar-light, making the button invisible.
In SoGive, Before this change:
After this change:

Set Navbar light property when darkTheme is false

---

base/components/MainDivBase.jsx

- Note that NavProps already included `children`, DefaultNavGuts rendered them, and `navbarChildren` was already unwrapped from MainDivBase props - but unused. This change fixes that by passing `navbarChildren` as the NavBar `children` property.
- Motivation for fixing this is to allow SoGive code to include a search widget in the NavBar (I will send a PR to sogive-app to start using navbarChildren today).

Fix support for navbar child components in MainDivBase

---

base/data/Advert.js

Check process.env for key RELEASE_BRANCH ("current branch, if it begins with (gl-)release") and autoset legacyUnitBranch on newly-created adverts

Advert: autoset legacyUnitBranch

---

base/data/GreenTag.js

Matching commits in adserver (backend support) and my-loop (create/manage interface)

Green Ad Tag: add front-end data type

---

base/components/PropControl.jsx

@athomson0 @winterstein 
Update propcontrol to reminder user if data between DRAFT & PUBLISHED are not the same. Hopefully preventing many future bugs.

first version

---

base/components/PropControls/PropControlUpload.jsx
base/plumbing/ServerIOBase.js
base/style/Misc.less

Needed by the matching branch in adserver. Adds some versatility to PropControlUpload for use in the green tag bulk uploader - allows overriding the endpoint & adding companion data (in this case, a template tag to merge with the CSV rows) on uploads.

Feature/2022 08/green tag bulk upload

---

base/components/ChartWidget.jsx

Hello,
This will add a "Download .csv" button beneath the widget shown in the "events over time" tab in the Portal dashboard reports section.
Can be seen here: https://localportal.good-loop.com/#dashboard?bby=vert&q=5BMfAc1OyI&start=2022-08-15&end=2022-08-25&server=production

add CSV export button to chartwidget

---

base/components/NavBar.jsx

Moving the brand logo into the collapse to handle my-loop new larger logo in desktop view. This touching the base code so better check if it would break other sites in testing first.

handle handle larger logo in new my-loop design

---

base/components/PropControl.jsx
base/style/PropControl.less

- Smaller (little badge inline with the label, rather than a large text label)
- More versatile (previous version could only diff top-level props on a DataItem, this one can index in arbitrarily)
- More informative (gives popover showing diff & clipboard button for pulling out bigger ones like customCSS)

Improve "unpublished edits" warning on PropControl

---

base/components/PropControlDataItem.jsx

Causes a behaviour change, so I'm calling for a sanity check before merge.
- If you type a valid item ID into its "search" box, PropControlDataItem will, without further interaction, turn your search box into a data-item badge.
- If you have - for instance - a campaign on the production portal with ID `T` (as we do), this can be a bad thing - especially as the search box doubles in many cases as a quick interface for creating a new data-item with a specified name.
- Old behaviour: I intend to create a test campaign and start typing "Test Campaign" --> I can't type any more because the PCDI says "Oh, `T`! I know this one! Here, I'll fill it in for you - no more search box."
- New behaviour: I type the first "T", PCDI's internal state says "The user has typed in the search box since the …

Bugfix/2022 11/pcdi no premature set

---

base/components/PropControls/PropControlCode.jsx
base/style/PropControl.less
base/style/prism-dark.less

this is the required changes for this PR: https://github.com/good-loop/adserver/pull/95
while working on that PR, found and fixed a few wee bugs with the syntax highlighting
- non-modal textareas wouldn't highlight when loaded - ref to highlight the element once its loaded
- pressing tab would cause the syntax to break in a weird way - just asking it to highlight after tab fixes it
Styling changes just change the CSS to look similar to CodePen but not identical due to Prism not differentiating between numerical and string values ('2.5vh' and 'transparent' for example) - so both values have the same colour. This wouldn't be a huge extra task but is beyond the scope of the current ticket.

changed highlight colours, fixed broken highlight on element loading and when pressing tab

---

base/components/PropControls/PropControlCode.jsx
base/style/PropControl.less
base/style/PropControls/PropControlCode.less

See the CSS box at the bottom of the Design tab on a Campaign page for why this is important.
Also allows it to assume its natural height - which means resizing can be enabled again.

PropControlCode: place textarea in-flow

---

base/style/PropControls/PropControlCode.less
base/style/prism-dark.less

firefox was setting textshadow when textarea was focused & not setting the inside of "pre" to the correct font, giving us the ghosting effect

fixed ghosting bug on firefox

---

base/components/PropControlDataItem.jsx

Fixes the case in portal where a Charity object is nulled out so its ID (storeValue for this component) is also null - but the PCDI still has a rawValue stored in useState, so it doesn't automatically turn back to a search box.

PropControlDataItem: don't retain picked value

---

base/components/PropControl.jsx

Currently shoves the checkbox to the right, then draws in a spot that overlaps it - this places it to the right of the label where you would expect

Put the diff marker in a less broken position on checkbox inputs

---

base/plumbing/ServerIOBase.js

- If user isn't on production (unprefixed domain) then APIBASE ends up as e.g. testtestportal
- ENDPOINT_NGO override is missing /charity path

Fix dodgy server=test behaviour on portal

---

base/data/Advert.js

Advert.viewcountByCampaign will now return an empty object if it got empty input, instead of just querying everything.

Bugfix/2022 12/viewcountbycampaign handle empty

---

project/.eslintrc.js

Fixes the ESLint error: `This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript'`

eslintrc tweak

---

base/components/ListLoad.jsx

See: https://github.com/good-loop/adserver/pull/120

canReadItem now also checks against canonical XIds now in order to support legacy users

---

base/components/PropControls/PropControlUpload.jsx

Didn't add it to the help text for the sake of brevity, but it's been added to the list as both extension and MIME type.

PropControlUpload recognises .webp as acceptable image file

---

base/components/ListLoad.jsx

required for a impact-overview feature when using nested ListLoads

ListItem wrappers can now have onClick's

---

base/components/ListLoad.jsx

as requested by @SaraGoodloop & @laurenwilso. In ListLoads with multiple pages, pages can be chosen from url & additional -10/+10 either direction buttons
requires PR : https://github.com/good-loop/adserver/pull/148

WIP: Feature/2023 03/listload page select

---

base/components/BlindUpload.jsx
base/components/propcontrols/PropControlUpload.jsx

Submits a file but doesn't put the response in a URL field / no implicit DataStore binding.
Used by MeasurePage in corresponding adserver branch.
Down the line, it probably makes sense to keep upload / dropzone logic only in here & import in PropControlUpload?

Add BlindUpload control

---

base/utils/date-utils.ts

Fixing an issue when we print the start/ end date in dashboard.
When we create `new Date(dateString)` in JavaScript. I will default to use the UTC +0 timezone. When we try to print the date in the browser, if our timezone is not UTC, the browser will adjust the time accordingly. i.e. The time will be +1 in BST time, or +7 in Hong Kong Time. 
This PR is to make our date object print as UTC. So the date shown in dashboard will be consistent whatever timezone you're in.

print period start end translate to local

---

base/utils/date-utils.ts

@winterstein Allowing asDate to consider timezone will fix the time slicing bug mentioned in https://mail.google.com/mail/u/0/#sent/QgrcJHshbMkDxwbMPCKPmprjQrrQdwcvwNG
Please merge if you think this is a correct way to fix this. Thanks.

Bugfix/2023 05/as date consider timezone

---

base/components/propcontrols/PropControlDt.jsx

Fixes the portal issue where standard video doesn't show new duration after an upload (the duration is set & saved and appears on reload, but because the PropControl component was already mounted it retained its local state of n=undefined, unit=undefined)

PropControlDt now detects updates in DataStore & pulls in changes

---

base/components/ListLoad.jsx
base/plumbing/Crud.js
base/style/ListLoad.less

- Detects when the hits count on a list-by-query is smaller than the actual item count, and fires off additional list requests with start-from-index param to get the rest of the items
- Preempts "too many IDs" error by breaking list-by-IDs requests into batches of 100 items
Effects can be seen at:
- Portal #advert page: all 2200+ items are loaded rather than silently pulling 1000 (cut to 500-odd with post-filtering)
- Green dashboard filters: all 1200+ campaigns are now loaded in the dropdown (previously cut to 1000)
- Green tag generator: should fix 431 error + incomplete CSV when exporting full unfiltered tag list

WIP (add large data handling in ListLoad) CRUD functions: automatically break down large list requests

---

base/plumbing/Crud.js

Issue found:
- User creates and publishes mostly-empty object
- User adds video, charities, etc in draft version, but does not publish these changes
- User makes further small edit, then publishes changes
- Publish-by-diff makes a minimal edit to mostly-empty published version
- Server syncs published version over draft version, dropping previous substantive edits to draft
There will be a way to do this correctly, but it needs very careful consideration and this is a live and highly damaging bug. Removing publish-by-diff entirely for now.

Remove publish-by-diff until further notice

---

base/components/propcontrols/PropControlDataItem.jsx

If the empty value is not preserved, changes will not be saved properly as the value will get merged back in on publish, see https://good-loop.monday.com/boards/2603585504/views/60487313/pulses/4512758505

Make the data item value empty on removal, not deleted

---

base/components/PageRecommendations.jsx

The information in the modal depends almost entirely on knowing how the image is used in-page, if it appears to be unused there's nothing to see (and an NPE to throw).

Creative recs: don't try to show extra-details modal for unused images

---

base/components/creative-recommendations/processImage.js

When "noWebp" control is unchecked, send request with `format=webp` - when checked, send with `format=''`. 
Depends on server-side change https://github.com/good-loop/adserver/pull/204 (default to original image format) to work properly.

Creative recs: use correct format params when calling /recompress

---

base/components/PageRecommendations.jsx
base/components/creative-recommendations/processImage.js

Some ad images are unsurprisingly on URLs trigger Firefox Enhanced Tracking Protection - this stops us loading them during the recommendation generation / preview process. Immediate fix is to load them through FileProxyServlet.

Creative recommendations: load images through proxy

---

base/searchquery.js

Makes the "collapse multiple ANDs" regex more permissive, changes the leading/trailing AND checks to regex, and adds another to collapse a lone "AND" to "".
See https://portal.good-loop.com/#advert when changing options in the "Served" dropdown for issues with old behaviour - the "all" and "Serving" options put some wrinkly expressions in the q= param.

SearchQuery: better cleanup of dangling ANDs from text form

---

base/components/SavePublishDeleteEtc.jsx

I've now seen the "delete button doesn't ask for confirmation" issue crop up twice. Should we just set it so we have to confirm with each delete? Struggle to think of a situation where a quick "are you sure?" will be detrimental.

enforces that all deletes should be confirmed

---

base/components/Pager.jsx

Some ListLoads with large amount (>5) have been lagging a good bit, flashing until they eventually freeze the page. I think I found the issue but I've got a few questions about it. 
As far as I understand it, we watch for the size of the list so we can add in page numbers & then mark it as measured. We then add in our page numbers.
The issue then arises from he fact that this changes the size of the element, meaning it needs remeasured. Since it isn't measured, we take out the page numbers (since we don't know what size & how many to use) & measure the page. Then we're back at the start of this loop.
To replicate the issue, head to https://portal.good-loop.com/?filter=#green -> bulk upload -> change the brand field
I'm a wee bit unsure on what situation where we'd need to remeasure this …

removed breaking var from useEffect

---

base/components/LoginWidget.jsx

When clicking the `send-verify` link on stageportal for re-sending the verification link, YouAgain throws a 500 because we aren't providing it with an `app` parameter:  
```
java.lang.NullPointerException: Argument 0 in stg@test.com@email
at com.winterwell.utils.Utils.check4null(Utils.java:64)
at com.winterwell.youagain.data.DB.findAuth(DB.java:48)
at com.winterwell.youagain.YouAgainServlet.doSendEmailVerify(YouAgainServlet.java:539)
```
DB.java:48:
```
Utils.check4null(app, xid);
```
I _think_ using C.app is the correct way to pass this, if not please let me know!
Thanks,
Aidan

send-verify - pass app + dataspace

---

base/plumbing/ServerIOBase.js
template/config/template_serverio_overrides.js
template/webpack.config.js

Old way: read overrides from host-specific config file `$hostname.js` (if it exists) when executing webpack.config.js; jam them into process.env as an object literal.
Drawbacks: Config file is only read once, so webpack must be restarted for edits to take effect; have to make further changes to webpack.config.js if we want to add other types of override.
New way: Check for a host-specific config file `$hostname.js` when executing webpack.config.js and insert its path in process.env; ServerIOBase loads the file with `require()` if it exists and pulls the overrides from its exports.
Expanding the config file to stuff other than endpoint overrides is just a matter of $hostname.js exporting another object and `require()`ing it where it's needed.
Edits made to template webpack.config.js and …

Refactor how ServerIO overrides are compiled in

---

base/components/Misc.jsx

- change "less than one second ago/in the future" to broadly-standard "just now"
- set `noUpdate` prop to turn off auto-updating behaviour
- change container by passing tagname/component as `Tag` prop

Misc.RelativeDate tweaks 

---

base/components/DevOnly.jsx

- Pass a component or tagname in the `Tag` prop to use it instead of `<div>`
- Set the `test` prop to show/hide on `Roles.isTester()` instead of `isDev()`
- Pass other supplied props

DevOnly component: custom tags/components, also allow testers

---

base/plumbing/DataStore.js

Basically:
- DataStore.fetch() always returns a PV.
- It's useful in many ways (eg useEffect) if it always returns the same PV for the same fetch.
- Right now it doesn't: the PV is stored and remains stable UNTIL the fetch resolves, and then gets discarded. Subsequent requests receive a new immediately-resolving PV every time.
- These changes makes it so that the PV returned for a fetch-in-progress and the PV for the same fetch after resolving are the same object.

DataStore: minor overhaul to how fetch PVs are stored

---

base/components/propcontrols/PropControlDataItem.jsx
base/style/PropControl.less

As on the tin. Stop React complaining there's a `<form>` in a `<form>`, stop Bootstrap's sizing bursting the PCDI input out of its container.

PropControlDataItem remove <Form> and fix overflow

---

base/components/ShareWidget.jsx

Resolves an issue with the "copy access link" button (eg on my-loop green dashboards) where the first time a link is generated for a given view, it uses the authed users's JWT instead of the new pseudo-user.

Fix "accidenally share own login" bug

---

base/components/ListLoad.jsx
base/components/propcontrols/PropControlDataItem.jsx

- Adds a prop to ListLoad to allow suppressing normal "scroll to top on page change" behaviour
- PCDI's dropdown list uses that prop

PropControlDataItem don't scroll when switching list page

---

base/components/propcontrols/PropControlCode.jsx

When you Ctrl+F for something in a PropControlCode & the textarea has to scroll to bring it into view, scrolling sync is lost between the highlighted text (visible) and the textarea you actually type in (invisible) - when you click and start typing, your text doesn't appear where you expect.
This makes the scrolling sync 2-way, so Ctrl+F (finds text in the visible element first, so scrolls that) and user scrolling (hits the invisible element first, as it's in front) both trigger it.

PropControlCode: Fix find-in-page weirdness

---

base/plumbing/DataStore.js

In response to a bug where a fetch PV was retaining the originally fetched value, but other DataStore activity overwrote the item at that path - so calls to fetch() and getValue() would yield different objects.
Reading fetch(path, fetchFn).value on a resolved fetch now calls getPath(path).
Assigning to fetch(path, fetchFn).value throws an error, so if there's naughty code that would break this, we'll find out about it.

DataStore fetch(): overwrite returned PV.value with implicit getPath getter

---

base/components/propcontrols/PropControlDataItem.jsx

It was unused (outside of studio) and had bitrotted at some point - basically some key logic no longer took into account the fact that `storeValue` isn't an ID in embed mode. I needed it working while untangling the AdvertPage charity editor, so I fixed it.

PropControlDataItem fix "embed" prop showing [object Object]

---

base/data/Advert.js
base/data/Advertiser.js
base/data/Campaign.js
base/data/DeprecatedImpactHubData.js
base/data/ImpactPageData.js

As briefly as possible:
- The Impact Overview page was showing weird data for users who were logged in, but didn't have full access to the focus brands/campaigns/whatever.
- This was due to CrudServlets post-filtering results based on share access.
- This could be mostly fixed by adding `access: 'public'` to the call params when fetching campaigns-for-brand and other such chained retrievals.
- A LOT of the fetch convenience functions in DataClass JS files were a very big mess and didn't expose promises or PVs where they should, making it unnecessarily difficult to compose and update them.
- So, big refactor. All those functions now expose the underlying CRUD PromiseValue (or synthesise one through DataStore.fetch), and apply `access: 'public'` to the fetch params.
While I was at it: …

Large cleanup of ImpagctPageData.js:getImpressionsByCampaignByCountry + attendant data-class refactors

---

base/components/SavePublishDeleteEtc.jsx

The PropControlDataItem for setting charities on an advert uses an array index for its prop name - saveDraftFnFactory thinks keys should only be strings.
Possibly other types should be accepted as well, but definitely strings and numerics should.

SavePublishDeleteEtc: saveDraftFnFactory to allow numeric keys

---

base/components/creative-recommendations/recommendation-utils.js

Doesn't persist any changes - just has the "startAnalysis" function type-check the `url`/`html`/`tag.creativeURL`/`tag.creativeHtml` fields before calling the server, and swap them if the wrong thing is in the wrong bucket.

Creative recommendations: silently fix misplaced URL/HTML, if detected

---

base/components/propcontrols/PropControlCode.jsx
base/style/PropControls/PropControlCode.less

Very fussy CSS tweaks to bring the highlighting overlay's linebreaks closer to the textarea.

PropControlCode: fix highlighting overlay linebreak sync

---

base/components/ShareWidget.jsx

Since we introduced the `oldestValid` DBAuth field (for revoke-previous-logins functionality) we've had an issue where, if a user generates a share-link for a resource they have previously shared (NB doesn't have to be the same dashboard view - just has to be the same key parent object, e.g. a Campaign), all share-links previously generated for that resource by that user are invalidated.
Actual root cause: the pseudo-user has the same XId every time, and is re-created with every share link, updating their `created` and `oldestValid` timestamp - meaning the JWTs attached to older share-links, which were created before now, are now out of date.
This adds a timestamp to the XId when creating a share-link, meaning (a) new shares of the same object by the same user don't invalidate previous …

Fix "click share link, prompted to log in" issue
