base/components/Counter.jsx
This was meant to go in a separate branch but I pushed it here by accident -
but this branch isnt being used anyway so shouldn't be an issue.
Made the counter component preserve 2 figures on pennies when present.
=> Counter component merge

base/components/Counter.jsx, base/utils/printer.js
Hello Ben
This PR simplifies the code a bit, fixes a bug where the updater kept running, and fixes some corner cases.
- Dan
=> fix corner cases

base/CBase.js
Messed up the pull request several times due to screwing up git - should finally be good!
=> Refractor CBase.js to refer to GLAppManifest.js

base/components/Counter.jsx, base/plumbing/ServerIOBase.js
Lets the counter use text-center instead of just right align
=> Added option for counter to be centered

base/components/LoginWidget.jsx
the LoginWidget will now close when a non-refreshing navigation is made
=> Login widget vanishes on navigation

base/components/BG.jsx, base/plumbing/ServerIOBase.js
Changes to BG required for Tabs for Good homepage
=> Improved sogive id parsing and added more styling to BG

base/components/E404Page.jsx, base/components/LoginWidget.jsx
Changes required for Tabs-for-good
=> Minor edits to login widget

base/components/BG.jsx
Required for tabs-for-good landing page - non essential but ideal
=> Added custom style overriding for background image

base/components/Misc.jsx
For new impact hub multiple ad support
=> New Misc.DateDuration component which Impact Hub depends on

ads.txt, base/components/BG.jsx, base/components/CloseButton.jsx, base/components/Editor3ColLayout.jsx, base/components/Misc.jsx, base/components/PageCard.jsx, base/components/SimpleTable.jsx, base/components/StyleBlock.jsx, base/components/TaskList.jsx, base/data/Advert.js, base/data/DataClass.js, base/style/SimpleTable.less, base/style/gridbox.less, base/style/main-base.less
This improves SimpleTable's scroll support + cleans up the settings with a big refactor.
It is NOT backwards compatible -- some settings have changed, also state-management.
So it should NOT be merged until after we release SoGive's Stripe update.
=> Feature/dec 2020/big scrolling table

base/data/Money.js
Encountering impact hub campaign with GBP and USD - this prevents errors when testing for low donations
=> Added currency conversion to compare Money

base/components/PropControl.jsx, base/data/Campaign.js, base/utils/miscutils.ts
Companion of pull request https://github.com/good-loop/my-loop/pull/27
=> Moved logic of impact hub ad filtering into Campaign.js

base/data/Campaign.js
More functions to make a useable Agency and Advertiser impact hub controls - 
fetchForAgency currently does not work, is not just fetching advertisers assigned to the correct agency, but is instead fetching 400 of them.
=> More fetching functions

base/CBase.js, base/Roles.js, base/components/Icon.jsx, base/components/LoginWidget.jsx, base/components/MainDivBase.jsx, base/components/Misc.jsx, base/data/Claim.js, base/data/Link.js, base/data/Person.js, base/plumbing/ServerIOBase.js, base/youagain.js
- Simplified Person.js to work with single `person` or multiple `persons`.
- Removed `getProfilesNow()` as a bug breeding ground.
- Added `hasApp`, `setHasApp` utility methods.
This is a matched PR with wwappbase.js
=> Bughunt/apr 2021/t4g

base/components/PropControls/PropControlUpload.jsx, base/plumbing/ServerIOBase.js
While an upload is uploading, this replaces the thumbnail with a readout of the size, percentage done, and ETA of the file in progress.
Merge with caution, as this will break uploading ENTIRELY unless the upload server has the following in its nginx config:
```
location / {
if ($request_method = OPTIONS ) {
add_header Access-Control-Allow-Origin $http_origin;
add_header Access-Control-Allow-Credentials true;
}
}
```
`testuploads.good-loop.com` has it, other upload servers do not.
=> Upload widget to print out status of upload in progress

base/components/PropControls/PropControlUpload.jsx
Accepts TTF, OTF, WOFF and WOFF2 fonts, and shows an editable sampler of the font whose URL is in the edit-box.
=> Add "fontUpload" type to PropControlUpload

base/plumbing/Crud.js, base/utils/DetectAdBlock.js
Still WIP, showing odd behaviour where general internet can be shown to succeed even when ethernet pulled.
=> Feature/2022 01/improved adblock detect

base/data/Money.js
@athomson0 I thought the new API currency converter was merged few months ago but turns out it was not. Could we add this to this month's testing and aim to have this live in our next release? Thanks.
=> Feature/2021 12/money currency convert

base/components/PropControl.jsx, base/style/PropControl.less
opening a modal now carries over your caret position from your text or textarea element
=> Feature/2022 08/modal propcontrol

base/components/NewChartWidget.jsx
as per @roscoemcinerney's request, moved NewChartWidget from my-loop into base & updated paths. No build errors on my end 
https://github.com/good-loop/my-loop/pull/102
=> moved NewChartWidget into base & updated paths

base/data/GreenTag.js
Paired with a PR in adserver: feature/2022-08/greentag-notes
=> Added notes field to Greentag data object

base/components/PropControlDataItem.jsx
Fixes space typing and premature item selection
=> Bugfix/2022 09/propcontroldataitem

base/Roles.js, base/Shares.js, base/components/BG.jsx, base/components/CardAccordion.jsx, base/components/Circle.jsx, base/components/DynImg.jsx, base/components/Icon.jsx, base/components/Misc.jsx, base/components/PropControlAutoComplete.jsx, base/components/PropControlDataItem.jsx, base/components/SavePublishDeleteEtc.jsx, base/components/ShareWidget.jsx, base/data/Advert.js, base/data/Branding.js, base/data/Claim.js, base/data/Impact.js, base/data/Money.js, base/data/NGO.js, base/data/Person.js, base/plumbing/Crud.js, base/plumbing/DataStore.js, base/promise-value.js, base/style/flex.less, base/utils/DetectAdBlock.js, base/utils/miscutils.ts, project/.eslintrc.js, template/package.json
Data class code and some bug-fixes.
Promise-value gets moved into local code (rather than being an npm package).
=> Feature/2022 11/impact hub overview page

base/Shares.js, base/components/AccountMenu.jsx, base/components/Icon.jsx, base/components/MainDivBase.jsx, base/components/ShareWidget.jsx, base/data/XId.js, base/youagain.js, project/.eslintrc.js
Support for share-by-link using a pseudo user
=> Feature/2022 12/share

base/components/NavBar.jsx, base/components/PortalLink.jsx, base/components/PropControl.jsx, base/searchquery.js
This allows e.g.
```
let [x, setX] = useState();
<PropControl value={x} set={setX} />
```
=> Feature/2022 12/prop control+use state

base/components/ShareWidget.jsx
Auto-populates the email address in the share widget
=> autopopulate share email if provided

base/components/AccountMenu.jsx, base/components/ShareWidget.jsx
Companion PR to https://github.com/good-loop/my-loop/pull/170
=> Bugfix/2023 02/account menu layout

base/components/Icon.jsx, base/components/Misc.jsx, base/components/NewChartWidget.jsx, base/components/PropControl.jsx, base/components/PropControls/PropControlPeriod.jsx, base/data/Impact.js, base/data/Money.js, base/plumbing/DataLog.js, base/plumbing/DataStore.js, project/.eslintrc.js
Fixes a bug where: if a data value changes, then PropControl [rawValue]=useState() won't update
Adds a PropControl wrapper for start+end
=> [dont merge until were finished with hotfixes] feature/2023-02/bugfix-rawValue-feature-PropControlPeriod

base/components/AccountPageWidgets.jsx, base/youagain.js
Allow user to send email verification to themselves in account dashboard. Front end codes.
=> Feature/2023 03/email verification

base/utils/miscutils.js, base/utils/miscutils_deprecated.ts
When I try to see if I could generate typescript declaration files for our internal classes written in js, I came across this file. This ts file gave many errors. Also there is a comment of `Should we switch back to .js over .ts??` at the beginning of the file. 
We should convert this back to js now and stop the error messages, so I could come back and write typescript declaration or a real typescript refactor later. 
But since this is a file that get used in many of our projects. I will make it into a PR instead of pushing this directly into master. Theoretically nothing will change after the merge. But just to be safe. @geoffballinger please let me know when you think it's the time to do the merge and testing. Thanks.
=> miscutils fall back to js

base/components/PropControl.jsx, base/components/propcontrols/PropControlDate.jsx, base/components/propcontrols/PropControlPeriod.jsx, base/utils/date-utils.ts
@winterstein I am glad that I asked about the url params date format yesterday, it all make sense now. This should work. (Still need testing, of course!)
=> Bugfix/2023 05/timezone

base/components/SimpleTable.jsx
simpletable to support significantDigits and precision in each cell
=> support for significantDigits and precision is simpletable

base/components/PageRecommendations.jsx, base/components/propcontrols/PropControlRange.tsx, base/components/propcontrols/PropControls.jsx, base/utils/pageAnalysisUtils.js
What it says on the tin. Worth noting it accepts the param "onChangeInstant" (maybe not final name/pattern) which skips the debouncing step this PropControl normally does to avoid spamming DataStore with drag events
=> Add PropControlRange to support green dashboard refactor in my-loop

base/data/DeprecatedImpactHubData.js
Values returned by the realtime part are almost always zero or negligible, and we're killing the endpoint it calls, so it now only pulls charity-to-donation maps explicitly set on campaigns.
=> Gut legacy/deprecated Campaign.dntn4charity

base/plumbing/Crud.js
Some refactor and cleanup in passing + edit jsdoc comments to be more ncompatible with TypeScript linting
=> Error in CRUD list-by-IDs: tried to access "arguments" inside arrow function

base/plumbing/Crud.js
Check for an existing PUBLISHED version of the item when publishing.
If it's absent, don't publish-by-diff - as the server doesn't have a published item to apply the diff to.
=> Fix issue where first publish of new item failed

base/components/GoodLoopUnit.jsx
Like recent changes in AdvertsCatalogue, checks for available space & how it relates to the advert aspect, then sets utility classes on the advert container to fix width relative to height or height relative to width.
=> GoodLoopUnit better container size detection

base/components/Toast.jsx, base/style/Toast.less, base/style/main-base.less
For portal/editors to show changes
=> (think and merge/refactor wanted) Toast component

base/components/BlindUpload.jsx, base/components/PageRecommendations.jsx, base/components/creative-recommendations/recommendation-utils.js, base/utils/pageAnalysisUtils.js
Add functionality to the creative measurement utility code which wasn't needed on my-loop creative recs page so it can be used on portal MeasurePage too
=> Creative recommendations / page measurement code refactor

base/components/PageRecommendations.jsx, base/components/creative-recommendations/recommendation-utils.js
No more trying to asynchronously shove recommendation items into the list as they come back from the server.
Also fix sorting of recommendation cards & always display cards for every resource - but "no improvement" ones sorted to the end.
=> Green recommendations: No flicker/jumping while loading

base/components/LoginWidget.jsx, base/youagain.js
=> allow A verification email to display after signup

base/utils/miscutils.js
Fixes a bug seen on Impact Overview when loading https://my.good-loop.com/impact/view/brand/VAcnHLcz?gl.status=DRAFT# - it tries to fetch resources with status=`DRAFT#`.
=> miscutils.js getUrlVars: # is not part of URL params

base/components/Icon.jsx, base/components/MDText.jsx, base/components/SubCard.jsx
Small harmless update but better wrap them in a PR.
=> update jsdoc to support typescript

template/config/localmyapp.good-loop.com.nginx
Updating template to normalise styling
=> Standardising local nginx config files

base/components/CSVUtils.ts
Code to handle CSV front end. @winterstein not sure if we have something like this yet. If not please merge. Thanks.
=> Feature/2023 09/csv utils

base/components/propcontrols/PropControlDataItem.jsx
They do weird things when they're not in a Bootstrap `<Container>`.
=> Remove <Row> and <Col> wrappers from PropControlDataItem

base/components/ListLoad.jsx, base/components/SavePublishDeleteEtc.jsx, base/plumbing/Crud.js
Pair to PR in adserver of same name
=> (reviewing) Listload load separate item for logo so it updates

base/components/PageRecommendations.jsx, base/components/creative-recommendations/processGeneric.js, base/components/creative-recommendations/processImage.js, base/components/creative-recommendations/recommendation-utils.js
Counterpart to https://github.com/good-loop/adserver/pull/223
=> Front-end changes to match RecompressServlet overhaul in adserver repo

base/components/MainDivBase.jsx
Somewhere in the mists of time, the error object which causes `<Page />` to be replaced by an error page in MainDivBase fell off the roof rack, leaving only a very uninformative message - this restores it & formats the accompanying stack trace so it's immediately readable.
=> Show the error on the error page

base/components/AccountPageWidgets.jsx, base/components/CopyButton.jsx, base/components/DataItemBadge.jsx, base/components/Icon.jsx, base/components/Misc.jsx, base/components/Pager.jsx, base/components/ShareWidget.jsx, base/components/propcontrols/PropControlDataItem.jsx, base/style/PropControl.less
- Add some more SVG icons & reduce use of questionably-applicable emoji
- Make more controls that behave like buttons into buttons (eg share button)
- Add prop spreading to a few components so they accept extras like `title`
=> Various improvements to buttons and button-like things

base/components/PropControl.jsx
The user doesn't care if a value used to be null/undefined and is now `""`, `[]` or `{}` (but they do care if it's `0` or `false`).
=> PropControl diff marker: don't show for "differently empty" like null vs ""

base/components/EditLock.jsx, base/plumbing/LongPoll.js, base/style/EditLock.less
=> Move front-end lock code from adserver

base/components/PageRecommendations.jsx, base/components/creative-recommendations/processGeneric.js, base/components/creative-recommendations/processImage.js, base/components/creative-recommendations/recommendation-utils.js
Fixes various minor glitches in recommendations page, some ticketed & some not
=> Bugfix/2023 10/recommendations misc

base/data/Advertiser.js, base/data/Agency.js
See https://good-loop.monday.com/boards/2603585504/pulses/4684874791
=> Advertiser/Agency.getChildren: use param access=public when applicable

base/components/PropControl.jsx
=> Add "revert to published version" button to PropControl diff marker

base/components/NavBar.jsx
See https://good-loop.monday.com/boards/2603585504/pulses/5573790366.
ListItems instances will automatically filter by nav context, which can contain multiple items - but only the most recently added will be visible & clearable in the nav bar. If that's cleared, there's still a context item that the user can't see or remove, but which causes list filtering.
With this change, clearing an item-type from nav context will check for other items in `CONTEXT` and place the first one found in the nav bar - so it's visible and can be cleared off as well.
=> Nav bar: Fall back to other context items on clear
